import type { Metadata } from "next";
import { Baloo_2, Inter } from "next/font/google";
import { BottomNav } from "@/components/shared/bottom-nav";
import { Footer } from "@/components/shared/footer";
import { MobileTopBar } from "@/components/shared/mobile-top-bar";
import { TopNav } from "@/components/shared/top-nav";
import "./globals.css";

const headingFont = Baloo_2({
  variable: "--font-heading-family",
  weight: ["500", "700"],
  subsets: ["latin"],
});

const bodyFont = Inter({
  variable: "--font-body-family",
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${headingFont.variable} ${bodyFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TopNav />
        <MobileTopBar />
        {children}
        <Footer />
        <BottomNav />
      </body>
    </html>
  );
}
