"""add paper fields to questions

Revision ID: a6ec428fcfe7
Revises: d0c976ece429
Create Date: 2026-09-07 15:55:41.047258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ec428fcfe7'
down_revision = 'd0c976ece429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('paper', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('section', sa.String(length=100), nullable=False))
    op.add_column('questions', sa.Column('question_number', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('question_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'question_number')
    op.drop_column('questions', 'section')
    op.drop_column('questions', 'paper')
    # ### end Alembic commands ###
