"""add question identity constraint

Revision ID: cad899938eff
Revises: a6ec428fcfe7
Create Date: 2026-09-07 16:06:45.823807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad899938eff'
down_revision: Union[str, Sequence[str], None] = 'a6ec428fcfe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_question_identity', 'questions', ['subject', 'year', 'paper', 'question_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_question_identity', 'questions', type_='unique')
    # ### end Alembic commands ###
